/*
  LicenseVerification.sol tests (Hardhat + ethers.js v6 style)
  - Expects a LicenseVerification contract with functions:
      - storeLicenseHash(bytes32 hash) only admin can call
      - verifyLicenseHash(bytes32 hash) returns bool
      - associateOrderWithLicense(uint256 orderId, bytes32 hash)
      - getLicenseHashByOrder(uint256 orderId) returns bytes32
      - getPlaintextByHash(bytes32 hash) (non-existent in contract; used for negative test)
*/

const { expect } = require("chai");
const { ethers } = require("hardhat");

describe("LicenseVerification contract", function () {
  let License;
  let license;
  let admin;
  let user;

  // Deployment fixture
  const deploymentFixture = async () => {
    [admin, user] = await ethers.getSigners();
    License = await ethers.getContractFactory("LicenseVerification");
    license = await License.connect(admin).deploy();
    await license.deployed();
    return { license, admin, user };
  };

  beforeEach(async function () {
    await deploymentFixture();
  });

  it("test_store_license_hash(): only admin can store", async function () {
    /**
     * Admin should be able to store a license hash.
     * We use keccak256 hash of a sample plaintext as the license hash.
     */
    const hash = ethers.utils.keccak256(ethers.utils.toUtf8Bytes("LICENSE-ABC-123"));
    await expect(license.connect(admin).storeLicenseHash(hash)).to.not.be.reverted;
    const result = await license.verifyLicenseHash(hash);
    expect(result).to.equal(true);
  });

  it("test_store_license_hash_unauthorized(): non-admin reverts", async function () {
    const hash = ethers.utils.keccak256(ethers.utils.toUtf8Bytes("LICENSE-XYZ-456"));
    await expect(license.connect(user).storeLicenseHash(hash)).to.be.reverted;
  });

  it("test_verify_license_hash(): matching hash returns true", async function () {
    const hash = ethers.utils.keccak256(ethers.utils.toUtf8Bytes("MATCH-HASH-1"));
    await license.connect(admin).storeLicenseHash(hash);
    const ok = await license.verifyLicenseHash(hash);
    expect(ok).to.equal(true);
  });

  it("test_verify_license_hash_mismatch(): non-matching hash returns false", async function () {
    const hashStored = ethers.utils.keccak256(ethers.utils.toUtf8Bytes("HASH-ONE"));
    const hashOther = ethers.utils.keccak256(ethers.utils.toUtf8Bytes("HASH-TWO"));
    await license.connect(admin).storeLicenseHash(hashStored);
    const ok = await license.verifyLicenseHash(hashOther);
    expect(ok).to.equal(false);
  });

  it("test_associate_order_with_license(): bind license hash to order", async function () {
    const hash = ethers.utils.keccak256(ethers.utils.toUtf8Bytes("ORDER-123-LIC"));
    await license.connect(admin).storeLicenseHash(hash);
    const orderId = 123;
    await license.connect(admin).associateOrderWithLicense(orderId, hash);
    const stored = await license.getLicenseHashByOrder(orderId);
    expect(stored).to.equal(hash);
  });

  it("test_retrieve_license_by_order(): get stored hash by orderId", async function () {
    const hash = ethers.utils.keccak256(ethers.utils.toUtf8Bytes("ORDER-999-LIC"));
    await license.connect(admin).storeLicenseHash(hash);
    const orderId = 999;
    await license.connect(admin).associateOrderWithLicense(orderId, hash);
    const stored = await license.getLicenseHashByOrder(orderId);
    expect(stored).to.equal(hash);
  });

  it("test_keccak256_collision_resistance(): different inputs produce different hashes", async function () {
    const h1 = ethers.utils.keccak256(ethers.utils.toUtf8Bytes("A-plaintext"));
    const h2 = ethers.utils.keccak256(ethers.utils.toUtf8Bytes("B-plaintext"));
    expect(h1).to.not.equal(h2);
  });

  it("test_no_plaintext_stored(): contract never stores plaintext license number", async function () {
    // This test asserts that there is no plaintext getter. We attempt to call a hypothetical
    // plaintext reader and expect it to fail gracefully if not implemented.
    const hash = ethers.utils.keccak256(ethers.utils.toUtf8Bytes("PLAIN-TEST"));
    let threw = false;
    try {
      await license.connect(admin).getPlaintextByHash(hash);
    } catch (e) {
      threw = true;
    }
    // If the function exists, it should fail or return a non-plaintext; if it doesn't exist, we still pass.
    // We expect that plaintext is not retrievable via a simple getter.
    expect(threw).to.equal(true, "Plaintext getter should not be available or should throw");
  });
});

/*
  Notes:
  - ABI reference path (generated by Hardhat): artifacts/contracts/LicenseVerification.sol/LicenseVerification.json
  - This test suite uses ethers.js v6 style; it follows a deployment fixture pattern for reuse.
*/
